Error handling for failed orblibs
Attempt to degrade more gracefully for errors like:
```
RuntimeError: cmd_orb_start exit code 0.
ERROR. Message: Note: The following floating-point exceptions are
signalling: IEEE_INVALID_FLAG IEEE_DIVIDE_BY_ZERO
STOP No triaxial deprojection possible
```
- previously these would raise a `RuntimeError` causing program to stop
- I've added `try/except` around `mod.get_orblib()` to prevent this

I've also added `try/accept` around :
- deleting directories of failed models, which sometimes failed, since
the `ml` directories did not exist (possibly related to change above)
- plotting routines in model iterator, which sometimes failed