Error handling for failed orblibs (#201)
* Error handling for failed orblibs

Attempt to degrade more gracefully for errors like:
```
RuntimeError: cmd_orb_start exit code 0.
ERROR. Message: Note: The following floating-point exceptions are
signalling: IEEE_INVALID_FLAG IEEE_DIVIDE_BY_ZERO
STOP No triaxial deprojection possible
```
- previously these would raise a `RuntimeError` causing program to stop
- I've added `try/except` around `mod.get_orblib()` to prevent this

I've also added `try/accept` around :
- deleting directories of failed models, which sometimes failed, since
the `ml` directories did not exist (possibly related to change above)
- plotting routines in model iterator, which sometimes failed

* Added warning and error messages to let users know what happened.

* The initial values for chi2 and kinchi2 as well as their values for failed models are now nan. At other instances that sort the (kin)chi2, select the n best models, or select models in a certain vicinity of the best (kin)chi2, nan-values are properly treated.
Still untested: how does plotter.py behave when there are nan-values in the (kin)chi2 columns?

* Some more fixed for nan chi2 values: Plotter, ParameterGenerator.
Added warning text to ModelInnerIterator.create_and_run_model: if an orblib needs to be calculated unexpectedly and this orblib shows in multiple places in prior iterations it may cause a Fortran error.

* Moved the check_specific_stopping_criteria methods from the subclasses LegacyGridSearch, GridWalk, and FullGrid to the ParameterGenerator class because they are identical.

* Bugfix: initial nan values for the chi2 caused the parameter generators to throw an exception during the 'special' combined iteration 0 and 1
Changed the data type for the strings in the all_models table to 'S256' to avoid warnings regarding the string length of the timestamp. The output format is not affected.

Co-authored-by: Thomas I. Maindl <thomas.maindl@sdb.ltd>